/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.border.Border;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;
import javax.swing.text.rtf.RTFEditorKit;
import interfaces.Observador;
import interfaces.Observado;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSlider;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;

/**
 *
 * @author Alfredo Silva
 */
public class Body extends javax.swing.JFrame implements Observador {

    /**
     * Creates new form Body
     */
    public Body(String nomeObservador, Observado observado, JTextPane pagina) {
        this.nomeObservador = nomeObservador;
        this.instancia = observado;
        this.pagina = pagina;
        observado.incluirObservador(this);
        pagina.setStyledDocument(pagina.getStyledDocument());
        initComponents();
        setLocationRelativeTo(null);
        this.pagina.setBorder(BorderFactory.createCompoundBorder(bordaPagina, BorderFactory.createEmptyBorder(2, bordaEsquerda, 2, bordaDireita)));
        limparFormatacao();
        atualizaLabelBarraDeStatus(arquivo);
        atualizar(pagina.getStyledDocument());
        instancia.notificarObservadores();
        this.setVisible(true);
    }
    
    /*public Body() {
        //this.observadores = new ArrayList<>();
        //this.nomeObservador = nomeObservador;
        //observado.incluirObservador(this);
        initComponents();
        //setExtendedState(MAXIMIZED_BOTH);
        pagina.setBorder(BorderFactory.createCompoundBorder(bordaPagina, BorderFactory.createEmptyBorder(2, bordaEsquerda, 2, bordaDireita)));
        limparFormatacao();
        atualizaLabelBarraDeStatus(arquivo);
    }*/
    
    @Override
    public void atualizar(StyledDocument conteudoPagina) {
        this.pagina.setStyledDocument(conteudoPagina);
        // DEVE SER MODIFICADO PARA ATUALIZAR EM REDE
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelAbasSuperiores4 = new javax.swing.JTabbedPane();
        abaArquivo4 = new javax.swing.JPanel();
        botaoSalvar4 = new javax.swing.JButton();
        botaoSalvarComo4 = new javax.swing.JButton();
        separadorArquivo5 = new javax.swing.JSeparator();
        botaoEncerrarSecao4 = new javax.swing.JButton();
        comboAbrir = new javax.swing.JComboBox<>();
        abaEditar = new javax.swing.JPanel();
        botaoNegrito = new javax.swing.JToggleButton();
        botaoItalico = new javax.swing.JToggleButton();
        botaoSublinhado = new javax.swing.JToggleButton();
        separadorEditar1 = new javax.swing.JSeparator();
        comboCorFonte = new javax.swing.JComboBox<>();
        comboFonte = new javax.swing.JComboBox<>();
        comboTamanhoFonte = new javax.swing.JComboBox<>();
        separadorEditar2 = new javax.swing.JSeparator();
        botaoAplicar = new javax.swing.JButton();
        botaoLimparFormatacao = new javax.swing.JButton();
        abaVisualizar = new javax.swing.JPanel();
        botaoModoNoturno = new javax.swing.JToggleButton();
        barraDeStatus = new javax.swing.JPanel();
        labelBarraDeStatus = new javax.swing.JLabel();
        controleDeslizanteMargemEsquerda = new javax.swing.JSlider();
        controleDeslizanteMargemDireita = new javax.swing.JSlider();
        painelDeRolagemPagina = new javax.swing.JScrollPane();
        pagina = new javax.swing.JTextPane();
        painelFundoEsquerdo = new javax.swing.JPanel();
        painelFundoDireito = new javax.swing.JPanel();
        painelSuperior1 = new javax.swing.JPanel();
        painelSuperior2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("αEditor");
        setName("body"); // NOI18N
        setSize(new java.awt.Dimension(0, 0));

        botaoSalvar4.setText("Salvar");
        botaoSalvar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoSalvarComo4.setText("Salvar como");
        botaoSalvarComo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarComoActionPerformed(evt);
            }
        });

        separadorArquivo5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        botaoEncerrarSecao4.setText("Encerrar seção");
        botaoEncerrarSecao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEncerrarSecaoActionPerformed(evt);
            }
        });

        comboAbrir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abrir", "TXT", "RTF" }));
        comboAbrir.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboAbrirItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout abaArquivo4Layout = new javax.swing.GroupLayout(abaArquivo4);
        abaArquivo4.setLayout(abaArquivo4Layout);
        abaArquivo4Layout.setHorizontalGroup(
            abaArquivo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaArquivo4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(botaoSalvar4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSalvarComo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorArquivo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEncerrarSecao4)
                .addContainerGap(420, Short.MAX_VALUE))
        );
        abaArquivo4Layout.setVerticalGroup(
            abaArquivo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaArquivo4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaArquivo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaArquivo4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(abaArquivo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoEncerrarSecao4)
                            .addGroup(abaArquivo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botaoSalvar4)
                                .addComponent(botaoSalvarComo4))
                            .addComponent(separadorArquivo5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(comboAbrir))
                .addContainerGap())
        );

        painelAbasSuperiores4.addTab("Arquivo", abaArquivo4);

        botaoNegrito.setText("<html><b>N</b></html>");
        botaoNegrito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoNegrito.setMargin(new java.awt.Insets(2, 2, 2, 2));

        botaoItalico.setText("<html><i>I</i></html>");
        botaoItalico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoItalico.setMargin(new java.awt.Insets(2, 2, 2, 2));

        botaoSublinhado.setText("<html><u>S</u></html>");
        botaoSublinhado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoSublinhado.setMargin(new java.awt.Insets(2, 2, 2, 2));

        separadorEditar1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        comboCorFonte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preto", "Vermelho", "Verde", "Azul", "Amarelo", "Laranja", "Rosa" }));

        comboFonte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arial", "Calibri", "Courier New", "Tahoma", "Times New Roman", "Verdana" }));
        comboFonte.setSelectedIndex(3);
        comboFonte.setSelectedItem(3);

        comboTamanhoFonte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12", "14", "16", "18", "20", "22", "24", "26", "28", "36", "48", "72" }));
        comboTamanhoFonte.setSelectedIndex(3);

        separadorEditar2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        botaoAplicar.setText("Aplicar");
        botaoAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAplicarActionPerformed(evt);
            }
        });

        botaoLimparFormatacao.setText("Limpar formatação");
        botaoLimparFormatacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparFormatacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaEditarLayout = new javax.swing.GroupLayout(abaEditar);
        abaEditar.setLayout(abaEditarLayout);
        abaEditarLayout.setHorizontalGroup(
            abaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoNegrito, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoItalico, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSublinhado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCorFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTamanhoFonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoLimparFormatacao)
                .addContainerGap(820, Short.MAX_VALUE))
        );
        abaEditarLayout.setVerticalGroup(
            abaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(abaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoAplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoLimparFormatacao))
                    .addComponent(separadorEditar2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separadorEditar1)
                    .addComponent(comboCorFonte, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboFonte, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboTamanhoFonte, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, abaEditarLayout.createSequentialGroup()
                        .addGroup(abaEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoNegrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoItalico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoSublinhado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        painelAbasSuperiores4.addTab("Editar", abaEditar);

        botaoModoNoturno.setText("Modo noturno");
        botaoModoNoturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoModoNoturnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaVisualizarLayout = new javax.swing.GroupLayout(abaVisualizar);
        abaVisualizar.setLayout(abaVisualizarLayout);
        abaVisualizarLayout.setHorizontalGroup(
            abaVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaVisualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoModoNoturno)
                .addContainerGap(1252, Short.MAX_VALUE))
        );
        abaVisualizarLayout.setVerticalGroup(
            abaVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaVisualizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoModoNoturno)
                .addContainerGap())
        );

        painelAbasSuperiores4.addTab("Visualizar", abaVisualizar);

        painelAbasSuperiores4.setSelectedIndex(1);

        barraDeStatus.setBackground(new java.awt.Color(221, 217, 209));
        barraDeStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        labelBarraDeStatus.setText("Lembre-se de salvar o arquivo.");

        javax.swing.GroupLayout barraDeStatusLayout = new javax.swing.GroupLayout(barraDeStatus);
        barraDeStatus.setLayout(barraDeStatusLayout);
        barraDeStatusLayout.setHorizontalGroup(
            barraDeStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraDeStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBarraDeStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barraDeStatusLayout.setVerticalGroup(
            barraDeStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraDeStatusLayout.createSequentialGroup()
                .addComponent(labelBarraDeStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelBarraDeStatus.getAccessibleContext().setAccessibleName("");

        controleDeslizanteMargemEsquerda.setMaximum(379);
        controleDeslizanteMargemEsquerda.setToolTipText("Margem esquerda");
        controleDeslizanteMargemEsquerda.setValue(100);
        controleDeslizanteMargemEsquerda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        controleDeslizanteMargemEsquerda.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                controleDeslizanteMargemEsquerdaStateChanged(evt);
            }
        });

        controleDeslizanteMargemDireita.setMaximum(379);
        controleDeslizanteMargemDireita.setToolTipText("Margem direita");
        controleDeslizanteMargemDireita.setValue(100);
        controleDeslizanteMargemDireita.setInverted(true);
        controleDeslizanteMargemDireita.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                controleDeslizanteMargemDireitaStateChanged(evt);
            }
        });

        pagina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paginaKeyTyped(evt);
            }
        });
        painelDeRolagemPagina.setViewportView(pagina);

        javax.swing.GroupLayout painelFundoEsquerdoLayout = new javax.swing.GroupLayout(painelFundoEsquerdo);
        painelFundoEsquerdo.setLayout(painelFundoEsquerdoLayout);
        painelFundoEsquerdoLayout.setHorizontalGroup(
            painelFundoEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelFundoEsquerdoLayout.setVerticalGroup(
            painelFundoEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelFundoDireitoLayout = new javax.swing.GroupLayout(painelFundoDireito);
        painelFundoDireito.setLayout(painelFundoDireitoLayout);
        painelFundoDireitoLayout.setHorizontalGroup(
            painelFundoDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelFundoDireitoLayout.setVerticalGroup(
            painelFundoDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelSuperior1Layout = new javax.swing.GroupLayout(painelSuperior1);
        painelSuperior1.setLayout(painelSuperior1Layout);
        painelSuperior1Layout.setHorizontalGroup(
            painelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelSuperior1Layout.setVerticalGroup(
            painelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelSuperior2Layout = new javax.swing.GroupLayout(painelSuperior2);
        painelSuperior2.setLayout(painelSuperior2Layout);
        painelSuperior2Layout.setHorizontalGroup(
            painelSuperior2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelSuperior2Layout.setVerticalGroup(
            painelSuperior2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAbasSuperiores4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelFundoEsquerdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(controleDeslizanteMargemEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(controleDeslizanteMargemDireita, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelSuperior2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelDeRolagemPagina)
                    .addComponent(painelSuperior1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(painelFundoDireito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(barraDeStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelAbasSuperiores4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelFundoEsquerdo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelSuperior1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(controleDeslizanteMargemEsquerda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(controleDeslizanteMargemDireita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addComponent(painelSuperior2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(painelDeRolagemPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelFundoDireito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(barraDeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paginaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paginaKeyTyped
        // ACHO QUE TEM QUE SER UM SINGLETON
        // Instancia única do pai, para ser usado aqui,
        // onde poderei chamar pai.notificarObservadores()
        try {
            atualizar(pagina.getStyledDocument());
            instancia.notificarObservadores();
        } catch (NullPointerException ex) {
            //JOptionPane.showMessageDialog(this, "O usuário provedor do documento encerrou a seção.\nEste documento não pode mais ser editado por você.", "Seção encerrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_paginaKeyTyped

    private void controleDeslizanteMargemDireitaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_controleDeslizanteMargemDireitaStateChanged
        bordaDireita = controleDeslizanteMargemDireita.getValue();
        pagina.setBorder(BorderFactory.createCompoundBorder(bordaPagina, BorderFactory.createEmptyBorder(2, bordaEsquerda, 2, bordaDireita)));
    }//GEN-LAST:event_controleDeslizanteMargemDireitaStateChanged

    private void controleDeslizanteMargemEsquerdaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_controleDeslizanteMargemEsquerdaStateChanged
        bordaEsquerda = controleDeslizanteMargemEsquerda.getValue();
        pagina.setBorder(BorderFactory.createCompoundBorder(bordaPagina, BorderFactory.createEmptyBorder(2, bordaEsquerda, 2, bordaDireita)));
    }//GEN-LAST:event_controleDeslizanteMargemEsquerdaStateChanged

    private void botaoLimparFormatacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparFormatacaoActionPerformed
        limparFormatacao();
    }//GEN-LAST:event_botaoLimparFormatacaoActionPerformed

    private void botaoAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAplicarActionPerformed
        fontStyle(botaoNegrito.isSelected(), botaoItalico.isSelected(), botaoSublinhado.isSelected(), fontMap(comboFonte.getSelectedIndex()), colorMap(comboCorFonte.getSelectedIndex()), fontSizeMap(comboTamanhoFonte.getSelectedIndex()), 1);
        botaoNegrito.setSelected(false);
        botaoItalico.setSelected(false);
        botaoSublinhado.setSelected(false);
    }//GEN-LAST:event_botaoAplicarActionPerformed

    private void botaoEncerrarSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEncerrarSecaoActionPerformed
        InitSection.getInstancia().getBodiesNames().remove(nomeObservador);
        pagina = null;
        arquivo = null;
        nomeObservador = null;
        this.dispose();
        InitSection.getInstancia().setVisible(true);
    }//GEN-LAST:event_botaoEncerrarSecaoActionPerformed

    private void botaoSalvarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarComoActionPerformed
        definirEstrategia();
        estrategia.escreverDocumento(pagina);
        atualizar(pagina.getStyledDocument());
        atualizaLabelBarraDeStatus(arquivo);
    }//GEN-LAST:event_botaoSalvarComoActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        definirEstrategia();
        estrategia.escreverDocumento(pagina);
        atualizar(pagina.getStyledDocument());
        atualizaLabelBarraDeStatus(arquivo);
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoModoNoturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoModoNoturnoActionPerformed
        fachada.pintar();
    }//GEN-LAST:event_botaoModoNoturnoActionPerformed

    private void comboAbrirItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboAbrirItemStateChanged
        if (comboAbrir.getSelectedIndex() != 0) {
            definirEstrategia();
            String texto = estrategia.lerDocumento();
            pagina.setText(texto);
            atualizar(pagina.getStyledDocument());
            this.arquivo = estrategia.getArquivo();
            atualizaLabelBarraDeStatus(arquivo);
        }
    }//GEN-LAST:event_comboAbrirItemStateChanged
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Body.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Body.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Body.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Body.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Body(nomeObservador, instancia, pagina).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaArquivo4;
    private javax.swing.JPanel abaEditar;
    private javax.swing.JPanel abaVisualizar;
    private javax.swing.JPanel barraDeStatus;
    private javax.swing.JButton botaoAplicar;
    private javax.swing.JButton botaoEncerrarSecao4;
    private javax.swing.JToggleButton botaoItalico;
    private javax.swing.JButton botaoLimparFormatacao;
    private javax.swing.JToggleButton botaoModoNoturno;
    private javax.swing.JToggleButton botaoNegrito;
    private javax.swing.JButton botaoSalvar4;
    private javax.swing.JButton botaoSalvarComo4;
    private javax.swing.JToggleButton botaoSublinhado;
    private javax.swing.JComboBox<String> comboAbrir;
    private javax.swing.JComboBox<String> comboCorFonte;
    private javax.swing.JComboBox<String> comboFonte;
    private javax.swing.JComboBox<String> comboTamanhoFonte;
    private javax.swing.JSlider controleDeslizanteMargemDireita;
    private javax.swing.JSlider controleDeslizanteMargemEsquerda;
    private javax.swing.JLabel labelBarraDeStatus;
    private static javax.swing.JTextPane pagina;
    private javax.swing.JTabbedPane painelAbasSuperiores4;
    private javax.swing.JScrollPane painelDeRolagemPagina;
    private javax.swing.JPanel painelFundoDireito;
    private javax.swing.JPanel painelFundoEsquerdo;
    private javax.swing.JPanel painelSuperior1;
    private javax.swing.JPanel painelSuperior2;
    private javax.swing.JSeparator separadorArquivo5;
    private javax.swing.JSeparator separadorEditar1;
    private javax.swing.JSeparator separadorEditar2;
    // End of variables declaration//GEN-END:variables
    // Personal variables declaration
    private Border bordaPagina = BorderFactory.createLineBorder(Color.WHITE);
    private javax.swing.JFileChooser fileSelector = new javax.swing.JFileChooser();
    private File arquivo;
    private int bordaEsquerda = 100;
    private int bordaDireita = 100;
    private Style normal;
    private Style negrito;
    private Style italico;
    private static String nomeObservador;
    private static Observado instancia;
    private interfaces.Estrategia estrategia;
    private Facade fachada = new Facade(this);
    // End of personal variables declaration

    /*private void initStyles() {
        normal = StyleContext.getDefaultStyleContext().getStyle(
                StyleContext.DEFAULT_STYLE);

        negrito = pagina.getStyledDocument().addStyle("bold", normal);
        StyleConstants.setBold(negrito, true);

        italico = pagina.getStyledDocument().addStyle("italic", normal);
        StyleConstants.setItalic(italico, true);
    }*/
    
    public String getNomeObservador() {
        return nomeObservador;
    }
    
    public void fontStyle(boolean bold, boolean italic, boolean under, String fontFamily, Color color, int size, int tipo){        
        String textSelected = null;
        int count = 0;
        int start = 0;
        int end = 0;
        try {
            end = pagina.getSelectionEnd();
            start = pagina.getSelectionStart();        
            count = pagina.getSelectedText().length();
            textSelected= pagina.getSelectedText();            
        } catch (NullPointerException e) {

        }


        SimpleAttributeSet attributes = new SimpleAttributeSet();                       
        StyleConstants.setBold(attributes, bold);
        StyleConstants.setUnderline(attributes, under);  
        StyleConstants.setItalic(attributes, italic);
        StyleConstants.setFirstLineIndent(attributes, 400);
        if(tipo == 1){
            StyleConstants.setFontFamily(attributes, fontFamily);
            StyleConstants.setForeground(attributes,color);
            StyleConstants.setFontSize(attributes, size);         
        }       
        if (textSelected != null) {            
            try {                                           
                pagina.getStyledDocument().remove(start,count);     

            } catch (BadLocationException ex) {
                //Logger.getLogger(Create.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                 pagina.getStyledDocument().insertString(start,textSelected , attributes);
                 pagina.select(start, end);
                 pagina.setSelectedTextColor(color);                                  
            } catch (BadLocationException ex) {
                 //Logger.getLogger(Create.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {            
            try {
                 pagina.getStyledDocument().insertString(pagina.getStyledDocument().getLength()," " , attributes);
            } catch (BadLocationException ex) {
                 //Logger.getLogger(Create.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }
    
    public void limparFormatacao() {
        fontStyle(false, false, false, fontMap(0), colorMap(0), fontSizeMap(4), 1);
        botaoNegrito.setSelected(false);
        botaoItalico.setSelected(false);
        botaoSublinhado.setSelected(false);
        comboFonte.setSelectedIndex(0);
        comboCorFonte.setSelectedIndex(0);
        comboTamanhoFonte.setSelectedIndex(4);
    }
    
    public void atualizaLabelBarraDeStatus(File file) {
        if (file != null) {
            this.labelBarraDeStatus.setText(file.getPath());
        } else {
            this.labelBarraDeStatus.setText("Lembre-se de salvar o arquivo.");
        }
    }
        
    public Color colorMap(int index) {
        switch (index) {
            case 0:
                return Color.BLACK;
            case 1:
                return Color.RED;
            case 2:
                return Color.GREEN;
            case 3:
                return Color.BLUE;
            case 4:
                return Color.YELLOW;
            case 5:
                return Color.ORANGE;
            case 6:
                return Color.PINK;
            default:
                return Color.BLACK;
        }
    }
    
    public String fontMap(int index) {
        switch (index) {
            case 0:
                return "Arial";
            case 1:
                return "Calibri";
            case 2:
                return "Courier New";
            case 3:
                return "Tahoma";
            case 4:
                return "Times New Roman";
            case 5:
                return "Verdana";
            default:
                return "Arial";
        }
    }
    
    public int fontSizeMap(int index) {
        switch (index) {
            case 0:
                return 8;
            case 1:
                return 9;
            case 2:
                return 10;
            case 3:
                return 11;
            case 4:
                return 12;
            case 5:
                return 14;
            case 6:
                return 16;
            case 7:
                return 18;
            case 8:
                return 20;
            case 9:
                return 22;
            case 10:
                return 24;
            case 11:
                return 26;
            case 12:
                return 28;
            case 13:
                return 36;
            case 14:
                return 48;
            case 15:
                return 72;
            default:
                return 12;
        }
    }
    
    public void definirEstrategia() {
        if (comboAbrir.getSelectedItem().equals("TXT")) {
            estrategia = new InterageTXT(arquivo);
        } else {
            estrategia = new InterageRTF(arquivo);
        }
    }

    public JPanel getPainelFundoDireito() {
        return painelFundoDireito;
    }

    public JPanel getPainelFundoEsquerdo() {
        return painelFundoEsquerdo;
    }

    public JPanel getPainelSuperior1() {
        return painelSuperior1;
    }

    public JPanel getPainelSuperior2() {
        return painelSuperior2;
    }

    public JSlider getControleDeslizanteMargemDireita() {
        return controleDeslizanteMargemDireita;
    }

    public JSlider getControleDeslizanteMargemEsquerda() {
        return controleDeslizanteMargemEsquerda;
    }

    public JToggleButton getBotaoModoNoturno() {
        return botaoModoNoturno;
    }

}
