/*
' * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.List;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JTextPane;

/**
 *
 * @author Alfredo Silva
 */
public class InitSection extends javax.swing.JFrame implements Observado {
    
    public static InitSection getInstancia() {
        if (instancia == null) {
            instancia = new InitSection();
        }
        return instancia;
    }
    
    @Override
    public void incluirObservador(Observador observador) {
        this.bodies.add(observador);
    }
    
    @Override
    public void removerObservador(Observador observador) {
        int index = this.bodies.indexOf(observador);
        if (index >= 0) {
            this.bodies.remove(observador);
        }
    }
    
    @Override
    public void notificarObservadores() {
        for (Observador observador : bodies) {
            observador.atualizar(this.pagina.getStyledDocument());
        }
    }
    
    /**
     * Creates new form AlphaEditor
     */
    private InitSection() {
        this.bodies = new ArrayList<>();
        this.pagina = new JTextPane();
        this.bodiesNames = new ArrayList<>();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoesRadioInitSection = new javax.swing.ButtonGroup();
        painelLogin = new javax.swing.JPanel();
        labelTituloLogin = new javax.swing.JLabel();
        labelNomeLogin = new javax.swing.JLabel();
        nomeTextLogin = new javax.swing.JTextField();
        labelIPLogin = new javax.swing.JLabel();
        IPTextLogin = new javax.swing.JTextField();
        botaoRadioCriarSecao = new javax.swing.JRadioButton();
        botaoRadioInserirLink = new javax.swing.JRadioButton();
        linkTextLogin = new javax.swing.JTextField();
        botaoEntrar = new javax.swing.JButton();
        botaoCriarSecao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("αEditor");

        painelLogin.setToolTipText("");

        labelTituloLogin.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        labelTituloLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloLogin.setText("<html><font color=\"#FF4500\"><b><i>α</i></b></font>Editor</html>");

        labelNomeLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNomeLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomeLogin.setText("Nome:");

        nomeTextLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextLoginActionPerformed(evt);
            }
        });

        labelIPLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelIPLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIPLogin.setText("IP:");

        IPTextLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPTextLoginActionPerformed(evt);
            }
        });

        botoesRadioInitSection.add(botaoRadioCriarSecao);
        botaoRadioCriarSecao.setSelected(true);
        botaoRadioCriarSecao.setText("Criar nova seção");
        botaoRadioCriarSecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRadioCriarSecaoActionPerformed(evt);
            }
        });

        botoesRadioInitSection.add(botaoRadioInserirLink);
        botaoRadioInserirLink.setText("Inserir link de seção");
        botaoRadioInserirLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRadioInserirLinkActionPerformed(evt);
            }
        });

        linkTextLogin.setToolTipText("");
        linkTextLogin.setEnabled(false);
        linkTextLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkTextLoginActionPerformed(evt);
            }
        });

        botaoEntrar.setText("Entrar");
        botaoEntrar.setEnabled(false);
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });

        botaoCriarSecao.setText("Criar seção");
        botaoCriarSecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarSecaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTituloLogin, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(botaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCriarSecao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoRadioCriarSecao)
                            .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(linkTextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nomeTextLogin)
                                .addComponent(labelNomeLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoRadioInserirLink))
                            .addComponent(IPTextLogin)
                            .addComponent(labelIPLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelTituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNomeLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeTextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(labelIPLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IPTextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(botaoRadioCriarSecao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoRadioInserirLink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(linkTextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEntrar)
                    .addComponent(botaoCriarSecao))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linkTextLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkTextLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_linkTextLoginActionPerformed

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        if (!(nomeTextLogin.getText().equals(""))) {
            int index = bodiesNames.indexOf(nomeTextLogin.getText());
            if (index >= 0) {
                JOptionPane.showMessageDialog(this, "Não foi possível iniciar a seção. O usuário informado já existe.", "Seção não iniciada", ERROR_MESSAGE);
            } else {
                if (botaoRadioInserirLink.isSelected()) {
                    String host = linkTextLogin.getText();
                    int porta = 5000;
                    String nome = nomeTextLogin.getText();
                    bodiesNames.add(nomeTextLogin.getText());
                    conexao = new Conexao(IPTextLogin.getText(), porta, nome);
                    Observador body = new Body(nomeTextLogin.getText(), this, pagina, conexao);
                    this.incluirObservador(body);
                } else {
                    try {
                        InetAddress localHost = InetAddress.getLocalHost();
                        String host = localHost.getHostName();
                        int porta = 8080;
                        String nome = nomeTextLogin.getText();
                        bodiesNames.add(nomeTextLogin.getText());
                        conexao = new Conexao(IPTextLogin.getText(), porta, nome);
                        Observador body = new Body(nomeTextLogin.getText(), this, pagina, conexao);
                        this.incluirObservador(body);
                    } catch (UnknownHostException ex) {
                        Logger.getLogger(InitSection.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível iniciar a seção. O usuário não foi informado.", "Seção não iniciada", ERROR_MESSAGE);
        }
        //this.dispose();
    }//GEN-LAST:event_botaoEntrarActionPerformed

    private void nomeTextLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextLoginActionPerformed

    private void botaoRadioInserirLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRadioInserirLinkActionPerformed
        if (botaoRadioCriarSecao.isSelected()) {
            linkTextLogin.setEnabled(false);
            botaoEntrar.setEnabled(false);
            botaoCriarSecao.setEnabled(true);
        } else {
            linkTextLogin.setEnabled(true);
            botaoEntrar.setEnabled(true);
            botaoCriarSecao.setEnabled(false);
        }
    }//GEN-LAST:event_botaoRadioInserirLinkActionPerformed

    private void botaoRadioCriarSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRadioCriarSecaoActionPerformed
        if (botaoRadioCriarSecao.isSelected()) {
            linkTextLogin.setEnabled(false);
            botaoEntrar.setEnabled(false);
            botaoCriarSecao.setEnabled(true);
        } else {
            linkTextLogin.setEnabled(true);
            botaoEntrar.setEnabled(true);
            botaoCriarSecao.setEnabled(false);
        }
    }//GEN-LAST:event_botaoRadioCriarSecaoActionPerformed

    private void botaoCriarSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarSecaoActionPerformed
        botaoEntrarActionPerformed(evt);
    }//GEN-LAST:event_botaoCriarSecaoActionPerformed

    private void IPTextLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPTextLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IPTextLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitSection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IPTextLogin;
    private javax.swing.JButton botaoCriarSecao;
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JRadioButton botaoRadioCriarSecao;
    private javax.swing.JRadioButton botaoRadioInserirLink;
    private javax.swing.ButtonGroup botoesRadioInitSection;
    private javax.swing.JLabel labelIPLogin;
    private javax.swing.JLabel labelNomeLogin;
    private javax.swing.JLabel labelTituloLogin;
    private javax.swing.JTextField linkTextLogin;
    private javax.swing.JTextField nomeTextLogin;
    private javax.swing.JPanel painelLogin;
    // End of variables declaration//GEN-END:variables
    // Personal variables declaration
    private static InitSection instancia = null;
    private List<Observador> bodies;
    private JTextPane pagina;
    private Conexao conexao;
    private List<String> bodiesNames;
    // End of personal variables declaration
    
    public List<String> getBodiesNames() {
        return bodiesNames;
    }
}
